# Generated by Django 2.2 on 2020-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='repositoryName',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
