# Generated by Django 2.2 on 2020-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_source_repositoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='repositoryId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
