# Generated by Django 2.2 on 2020-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_source_repositoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='repositoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
