# Generated by Django 2.2 on 2020-12-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201220_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterField(
            model_name='repositorie',
            name='baseId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
